[project]
name = "multi-baker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.2",
    "click>=8.3.1",
    "mypy>=1.19.0",
    "pre-commit>=4.5.0",
    "requests>=2.32.5",
    "ruff>=0.14.8",
]
